language: node_js
node_js:
  - '10'
  - '8'
  - '6'
sudo: false
script: ./tool/travis.sh

services:
  - docker

before_install:
  - sudo service mysql stop
  - docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql
  - chmod +x ./tool/travis.sh
  - npm install -g ava

after_success:
  - npm run coverage

deploy:
  provider: npm
  email: "hugo.armstrong@gmail.com"
  api_key: $api_key
  on:
    tags: true
